name: test-vars

on: 
  workflow_dispatch:

jobs:
  display-variables:
    runs-on: ubuntu-latest
    environment: dev
    steps:        
    - name: Test composite
      uses: VarzTestOrg/addash-composite-action@main
