name: test-vars

on: 
  workflow_dispatch:

jobs:
  display-variables:
    runs-on: ubuntu-latest
    environment: dev
    steps:        
    - name: Use variables
      run: |
        echo "repo variable : ${{ vars[format('{0}_a', vars.foo)] }}"
        echo "org variable large : ${{ vars.LARGE_VAR }}"
        echo "large variable name test : ${{vars.test_var_name_recursive_test_var_name_recursive_test_var_name_recursive_test_var_name_recursive_test_var_name_recursive_test_var_name_recursive_test_var_name_recursive_test_var_name_recursive_test_var_name_recursive_recursive_test_var_name_recursive_test_var_name_recursive_test_var_name_recursive}}"
